version: "3"
services:
  app:
    container_name: swapi
    image: swapi
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      NODE_ENV: docker
      REDIS_URL: redis://cache
    ports:
        - "8081:8081"
    depends_on:
      - db
      - redis


  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: swapi

  redis:
    image: redis
    container_name: cache
    expose:
      - 6379
